### ISSUE TITLE
PSR-1/PSR-2 compliance

### ISSUE THREAD

**Issue by camuthig** [airshiphq/airship-php#1]
I am curious if you are open to a PR that applies PSR-1 and PSR-2 conventions to the codebase. Some things that would be fixed would include: 

* Method names MUST be declared in camelCase().
* Opening braces for classes MUST go on the next line, and closing braces MUST go on the next line after the body.
* Opening braces for methods MUST go on the next line, and closing braces MUST go on the next line after the body.
* The PHP constants true, false, and null MUST be in lower case.

While it is purposefully not defined by the PSR standards, I am also curious if you would be open to transitioning variables names to camelCase to keep naming conventions consistent across functions and variables in the project.

If you are open to it, I would be happy to create a PR as well as add tooling to help lint the code. Let me know!

**Comment by glusa8** [comment]
@camuthig thanks for raising the issue. Please feel free to open the PR.
