### ISSUE TITLE
Ignore the composer.lock file

### ISSUE THREAD

**Issue by camuthig** [airshiphq/airship-php#6]
There is no hard and fast rule on [committing a library's composer.lock file]9https://getcomposer.org/doc/02-libraries.md#lock-file). However, it can be helpful to remove the file and generally test against the lowest possible dependency version (`--prefer-lowest` with composer) to help catch bugs users may find and to test against different versions of PHP. Do you have any issues with adding the composer.lock file to .gitignore?

**Comment by glusa8** [comment]
No, I don't. I will remove it.

**Comment by glusa8** [comment]
Closing issue.
